//                     Copyright (c) 2007 - 2021 Synopsys, Inc.
//    This software and the associated documentation are proprietary to Synopsys,
//  Inc. This software may only be used in accordance with the terms and conditions
//  of a written license agreement with Synopsys, Inc. All other use, reproduction,
//    or distribution of this software is strictly prohibited.  Licensed Products
//      communicate with Synopsys servers for the purpose of providing software
//     updates, detecting software piracy and verifying that customers are using
//     Licensed Products in conformity with the applicable License Key for such
//   Licensed Products. Synopsys will use information gathered in connection with
//     this process to deliver software updates and pursue software pirates and
//                                    infringers.
// 
//  Inclusivity & Diversity - Visit SolvNetPlus to read the "Synopsys Statement on
//             Inclusivity and Diversity" (Refer to article 000036315 at
//                         https://solvnetplus.synopsys.com)
//
// MAX TB Test Protocol File, generated by MAX TB Version R-2020.09-SP5
// Mon Jan 19 15:56:15 2026
// Module under test: top
// Generated from original STIL file : "top_dft.stil"
// STIL file version: "1.0"
// Enhanced Runtime Version: use <sim_exec> +tmax_help for available runtime options
// Simulation mode: default parallel simulation

`define TDATA_FILE "/home/m110/m110063553/MBIST/atpg_out/top_dft_tb.dat"
`ifndef XTB_DUT_HIER 
  `define XTB_DUT_HIER dut
`endif
`timescale 1ns/1ns

// OPCODE DEFINITION
`define EndPat 0
`define IncPat 1
`define SetPat 2
`define WFTStmt 3
`define ConditionStmt 4
`define VectorStmt 5
`define FixedStmt 6
`define GenLoopStmt 7
`define EndGenLoopStmt 8
`define GenTestSetupStmt 9
`define EndGenTestSetupStmt 10
`define SetForceSI 11
`define SetValidStrobe 12
`define AnnotationStmt 13
`define SetWPack 14
`define SetRPack 15
`define test_setupStmt 16
`define load_unloadStmt 17
`define multiclock_captureStmt 18

// SIGS DEFINITION
`define clk 0
`define rst_n 1
`define bist_start 2
`define \bist_resp[1]  3
`define \bist_resp[0]  4
`define test_si 5
`define test_se 6
`define bist_cs 7
`define bist_we 8
`define \bist_addr[3]  9
`define \bist_addr[2]  10
`define \bist_addr[1]  11
`define \bist_addr[0]  12
`define \bist_pat[1]  13
`define \bist_pat[0]  14
`define bist_done 15
`define pass_or_fail 16
`define _pi 17
`define all_inputs 18
`define _po 19
`define _si 20
`define all_outputs 21
`define _clk 22
`define _so 23

// WFTS DEFINITION
`define _multiclock_capture_WFT_ 0
`define _default_WFT_ 1
`define MAX_PART 0

`define MAXTB_HEADER " MAX TB Version R-2020.09-SP5\n Test Protocol File generated from original file \"top_dft.stil\"\n STIL file version: 1.0"
`define MAXTB_H_S "#############################################################################"


module /* maxtb */ top_test ();
   parameter NSTMTS = 19; // number of all stmts
   parameter DFSHIFTS = 0; // (default) number of serial shifts in parallel scan mode
   parameter NAMELENGTH = 200; // max length of names reported in fails
   parameter FILELENGTH = 1024; // max length for file names 
   parameter MAXCHLEN = 21, NCHAINS = 1;
   parameter NINPUTS = 7, NOUTPUTS = 10, CUM_WIDTH=55;
   parameter NSIS = 1, NSOUTS = 1;
   parameter WFT_IDS = 2, SIG_IDS = 24, SIG_IDS_W = 5, MAX_WIDTH = 10, MAX_SIGW = 1;
   parameter PARSERINC = 21; 
   parameter SYNC_LATENCY = 3; 
   parameter PRTIME = 0.000000; 
   integer xtb_sim_mode; // simulation modes: xtb_sim_mode=0 -> serial, xtb_sim_mode=1 -> parallel (default);
   integer nbfails, abit, cbit;
   integer prev_error; // flag for tracking displayed error banner
   integer loads;        // number of load_unloads for current pattern
   integer prev_pat;     // previous pattern number;
   integer rep_pat; // report pattern progress every Nth pattern
   integer verbose;      // message verbosity level
   integer debug;      // enable debug level
   integer test_setup_runs; // counts the number of executed test_setups
   integer test_setup_only_once; // flag to trigger only one execution of test_setup
   integer data_i, n, cur_pat, start_pat, end_pat, last_pat, total_pats, csci, fsci, cur_stmt;
   integer v_count, v_count_per_pat;  // track the cycle count and cycle/pattern count (helpful for the simulator GUI)
   integer SSHIFTS;
   integer diagf, diagm;
   integer sertmg;
   integer the_wft_id, wft_id_s;
   integer ser_pats;
   integer first_pat;
   event start_part, end_part;
   `define NBRTOPS 7
   integer csim_op;
   reg [32*8:1] RT_OPS [0:`NBRTOPS];
   integer      rt_ops [0:`NBRTOPS-1];
   integer      tdfm;
   integer lp_addr, lp_count, lp_max;
   reg [0:(8*FILELENGTH)-1] TDATA_FILE;

   reg [MAX_SIGW*(NINPUTS+NOUTPUTS)-1:0] ALLINSIGS, ALLOUTSIGS;
   reg [MAX_SIGW*(NINPUTS+NOUTPUTS)-1:0] TMPINSIGS_V,TMPINSIGS_T,TMPINSIGS_V_S,TMPINSIGS_T_S;
   reg [MAX_SIGW*(NINPUTS+NOUTPUTS)-1:0] TMPOUTSIGS_V,TMPOUTSIGS_T,TMPOUTSIGS_V_S,TMPOUTSIGS_T_S;
   reg [NINPUTS+NOUTPUTS-1:0] ALLINSIGIDS, ALLOUTSIGIDS, ALLINSIGIDS_S, ALLOUTSIGIDS_S;
   reg [NSTMTS-1:0] opcode, popcode;
   event force_scells;
   event strobe_scells;
   event release_scells;
   reg [43:0] memel, memall [1:237];
   reg [0:(8*NAMELENGTH)-1] CH_NAMES [0:NCHAINS-1];
   reg [0:(8*NAMELENGTH)-1] CH_PINS [0:NCHAINS-1];
   reg [0:MAXCHLEN-1] LOD, LOAD[0:NCHAINS-1];
   reg [0:MAXCHLEN-1] UNL, UNLOAD[0:NCHAINS-1];
   reg [0:MAXCHLEN-1] UNLM;
   reg [0:MAXCHLEN-1] SERIALM;
   reg [0:MAXCHLEN-1] CH_INPINV[0:NCHAINS-1], CH_OUTINV[0:NCHAINS-1];
   wire [0:NCHAINS-1] SCANOUT;
   reg [0:MAXCHLEN-1] CHOUT, CHAINOUT[0:NCHAINS-1];
   reg [0:MAXCHLEN-1] CHAINOUT0;
   reg [0:MAXCHLEN-1] LOD0;
   reg strobe_en;
   reg [SIG_IDS-1:0] sid_args ;
   reg [2*CUM_WIDTH-1:0] sval_args;
   reg [4:0] the_sids [0:SIG_IDS-1];
   reg [8*NAMELENGTH-1:0]  SignalIDName [0:23];
   reg [2:0]  SignalIDType [0:23];
   reg [3:0]  SignalIDWidth [0:23];
   reg [(8*NAMELENGTH-1):0]  WFTIDName [0:1];
   reg [0:(8*FILELENGTH)-1] diag_file;
   reg [0:(8*NAMELENGTH-1)] StmtNames [0:NSTMTS];

   reg clk_con ;
   reg rst_n_con ;
   reg bist_start_con ;
   reg \bist_resp[1]  ;
   reg \bist_resp[0]  ;
   reg test_si_con ;
   reg test_se_con ;
   wire bist_cs_con ;
   wire bist_we_con ;
   wire \bist_addr[3]  ;
   wire \bist_addr[2]  ;
   wire \bist_addr[1]  ;
   wire \bist_addr[0]  ;
   wire \bist_pat[1]  ;
   wire \bist_pat[0]  ;
   wire bist_done_con ;
   wire pass_or_fail_con ;

   wire [0:(8*NAMELENGTH-1)] cur_StmtName;
   assign cur_StmtName = StmtNames[cur_stmt] ;


   top dut ( 
     .clk ( clk_con ),
     .rst_n ( rst_n_con ),
     .bist_start ( bist_start_con ),
     .bist_resp ( { \bist_resp[1] ,
        \bist_resp[0] } ),
     .test_si ( test_si_con ),
     .test_se ( test_se_con ),
     .bist_cs ( bist_cs_con ),
     .bist_we ( bist_we_con ),
     .bist_addr ( { \bist_addr[3] ,
        \bist_addr[2] ,
        \bist_addr[1] ,
        \bist_addr[0] } ),
     .bist_pat ( { \bist_pat[1] ,
        \bist_pat[0] } ),
     .bist_done ( bist_done_con ),
     .pass_or_fail ( pass_or_fail_con )
  );
  
  // Inject error
  // force net n1 to 0
  //initial force dut.i_bist_controller.n1 = 0;

   task save_context;
     begin
       wft_id_s = the_wft_id;
       TMPINSIGS_V_S = TMPINSIGS_V;
       TMPOUTSIGS_V_S = TMPOUTSIGS_V;
       TMPINSIGS_T_S = TMPINSIGS_T;
       TMPOUTSIGS_T_S = TMPOUTSIGS_T;
       ALLOUTSIGIDS_S = ALLOUTSIGIDS;
       ALLINSIGIDS_S = ALLINSIGIDS;
     end
   endtask 

   task restore_context;
     begin
       the_wft_id = wft_id_s;
       TMPINSIGS_V = TMPINSIGS_V_S;
       TMPOUTSIGS_V = TMPOUTSIGS_V_S;
       TMPINSIGS_T = TMPINSIGS_T_S;
       TMPOUTSIGS_T = TMPOUTSIGS_T_S;
       ALLOUTSIGIDS = ALLOUTSIGIDS_S;
       ALLINSIGIDS = ALLINSIGIDS_S;
     end
   endtask 

   task resolve_signal;
     input reg [4:0] sid;
   begin
     if (SignalIDType[sid] != 3) the_sids[0] = sid;
     else begin
       case (sid)
         'd17: begin // _pi
                 the_sids[6] = 4; the_sids[5] = 3; the_sids[4] = 2; the_sids[3] = 0; the_sids[2] = 1; the_sids[1] = 5;
                 the_sids[0] = 6;
               end
         'd18: begin // all_inputs
                 the_sids[6] = 4; the_sids[5] = 3; the_sids[4] = 2; the_sids[3] = 0; the_sids[2] = 1; the_sids[1] = 5;
                 the_sids[0] = 6;
               end
         'd19: begin // _po
                 the_sids[9] = 12; the_sids[8] = 11; the_sids[7] = 10; the_sids[6] = 9; the_sids[5] = 7; the_sids[4] = 15; the_sids[3] = 14; the_sids[2] = 13; the_sids[1] = 8;
                 the_sids[0] = 16;
               end
         'd20: begin // _si
                
                 the_sids[0] = 5;
               end
         'd21: begin // all_outputs
                 the_sids[9] = 12; the_sids[8] = 11; the_sids[7] = 10; the_sids[6] = 9; the_sids[5] = 7; the_sids[4] = 15; the_sids[3] = 14; the_sids[2] = 13; the_sids[1] = 8;
                 the_sids[0] = 16;
               end
         'd22: begin // _clk
                 the_sids[1] = 0;
                 the_sids[0] = 1;
               end
         'd23: begin // _so
                
                 the_sids[0] = 13;
               end
          default: begin $display("\nXTB Error: unrecognized signal id %d (valid range is 0..%d). Exiting...",sid, SIG_IDS); $finish; end
       endcase
     end
   end
   endtask

   task get_stb_sig;
     input reg [4:0] sid ;
     output reg [MAX_WIDTH-1:0] strsig;
   begin
     case (sid)
       'd7:	strsig[0:0] = 	bist_cs_con ;
       'd8:	strsig[0:0] = 	bist_we_con ;
       'd9:	strsig[0:0] = 	\bist_addr[3]  ;
       'd10:	strsig[0:0] = 	\bist_addr[2]  ;
       'd11:	strsig[0:0] = 	\bist_addr[1]  ;
       'd12:	strsig[0:0] = 	\bist_addr[0]  ;
       'd13:	strsig[0:0] = 	\bist_pat[1]  ;
       'd14:	strsig[0:0] = 	\bist_pat[0]  ;
       'd15:	strsig[0:0] = 	bist_done_con ;
       'd16:	strsig[0:0] = 	pass_or_fail_con ;
       default: begin $display("\nXTB Error: unrecognized output signal id %d. Exiting...",sid); $finish; end
     endcase
   end
   endtask

   task set_force_sig;
     input reg [SIG_IDS-1:0] sid ;
   begin
     case (sid)
       'd0: clk_con 	= ALLINSIGS[sid];
       'd1: rst_n_con 	= ALLINSIGS[sid];
       'd2: bist_start_con 	= ALLINSIGS[sid];
       'd3: \bist_resp[1]  	= ALLINSIGS[sid];
       'd4: \bist_resp[0]  	= ALLINSIGS[sid];
       'd5: test_si_con 	= ALLINSIGS[sid];
       'd6: test_se_con 	= ALLINSIGS[sid];
       default: begin $display("\nXTB Error: unrecognized (input) signal id %d (valid range is 0..%d). Exiting...",sid, SIG_IDS-1); $finish; end
     endcase
   end
   endtask 

   always  begin: force_sigs_p
     reg [SIG_IDS-1:0] sid; 
     reg [MAX_SIGW-1:0] sig;
     fork
        forever @(ALLINSIGS[0]) set_force_sig('d`clk );
        forever @(ALLINSIGS[1]) set_force_sig('d`rst_n );
        forever @(ALLINSIGS[2]) set_force_sig('d`bist_start );
        forever @(ALLINSIGS[3]) set_force_sig('d`\bist_resp[1]  );
        forever @(ALLINSIGS[4]) set_force_sig('d`\bist_resp[0]  );
        forever @(ALLINSIGS[5]) set_force_sig('d`test_si );
        forever @(ALLINSIGS[6]) set_force_sig('d`test_se );
     join
   end

   task measure_out_sig;
     input reg [SIG_IDS-1:0] sid ;
     input integer  stmtid;
     reg [MAX_WIDTH-1:0] xsig;
     reg [MAX_WIDTH-1:0] csig;
     integer errshown, abit, cpat;
   begin
     errshown = 0;
     cpat = cur_pat < 0 ? 0 : cur_pat;
     get_stb_sig(sid,csig);
     xsig = ALLOUTSIGS[sid ];
     for (abit = 0; abit < SignalIDWidth[sid]; abit = abit + 1) begin
       if (xsig[abit] !== 1'bx) begin
         if (xsig[abit] !== csig[abit]) begin
           if (errshown == 0) $display(">>>  Error during %0s pattern %0d", StmtNames[stmtid], cpat);
           if (SignalIDWidth[sid] <= 1) begin 
             $display(">>>  \tAt T=%0t, V=%0d, exp=%b, got=%b, signal %0s", $time, v_count, xsig[abit], csig[abit], SignalIDName[sid]);
             if (diagf) begin 
               if (diagm==2) $fdisplay(diagf, "  C %0s %0d (exp=%b, got=%b)", SignalIDName[sid], v_count, xsig[abit], csig[abit]);
               else $fdisplay(diagf, "  %0d %0s (exp=%b, got=%b)", cpat, SignalIDName[sid], xsig[abit], csig[abit]);
             end 
           end 
           else begin 
             $display(">>>  \tAt T=%0t, V=%0d, exp=%b, got=%b, signal %0s[%0d]", $time, v_count, xsig[abit], csig[abit], SignalIDName[sid], abit);
             if (diagf) begin 
               if (diagm==2) $fdisplay(diagf, "  C %0s[%0d] %0d (exp=%b, got=%b)", SignalIDName[sid], abit, v_count, xsig[abit], csig[abit]);
               else $fdisplay(diagf, "  %0d %0s[%d] (exp=%b, got=%b)", cpat, SignalIDName[sid], abit, xsig[abit], csig[abit]);
             end 
           end 
           nbfails = nbfails + 1;
           errshown = 1;
         end 
       end 
     end 
   end 
   endtask

   task measure_scan_out;
     input reg [SIG_IDS-1:0] sid ;
     input integer  chain;
     reg [MAX_WIDTH-1:0] xsig;
     reg [MAX_WIDTH-1:0] csig;
     integer errshown, patoff;
   begin
     errshown = 0;
     get_stb_sig(sid, csig);
     xsig = ALLOUTSIGS[sid ];
     if ((xsig[0] !==1'bx) && (xsig[0] !== csig[0])) begin
       patoff = (loads > 1 || cur_pat <= 0) ? 0 : 1;
       if (prev_error != cur_pat) begin
         if (cur_pat <= 0 || cur_pat == last_pat && loads > 1) begin
           $display(">>>  Error during scan pattern %0d %s", (cur_pat < 0) ? 0 : cur_pat,  (cur_pat == last_pat) ? "(detected from final pattern unload)" : "");
         end
         else begin
           if (loads > 1) $display(">>>  Error during scan pattern %0d (detected from %0d load/unload)", cur_pat, loads);
           else begin $display(">>>  Error during scan pattern %0d (detected from unload of pattern %0d)", cur_pat, cur_pat-1); end
         end 
         prev_error = cur_pat;
       end
       $display(">>>  \tAt T=%0t, V=%0d, exp=%b, got=%b, chain %0s, pin %0s, scan cell %0d", $time, v_count, xsig[0], csig[0], CH_NAMES[chain], SignalIDName[sid], fsci);
       if (diagf) begin 
         if (diagm==2) $fdisplay(diagf, "  C %0s %0d (exp=%b, got=%b)", SignalIDName[sid], v_count, xsig[0], csig[0]);
          else $fdisplay(diagf, "  %0d %0s %0d (exp=%b, got=%b)", cur_pat-patoff, SignalIDName[sid], fsci, xsig[0], csig[0]);
       end 
       nbfails = nbfails + 1;
     end
   end 
   endtask

   always begin: measure_sigs_p
    fork
     forever @(ALLOUTSIGS['d`bist_cs]) begin
       #0 if (cur_stmt == `VectorStmt || cur_stmt == `multiclock_captureStmt ) measure_out_sig('d`bist_cs, cur_stmt); 
     end
     forever @(ALLOUTSIGS['d`bist_we]) begin
       #0 if (cur_stmt == `VectorStmt || cur_stmt == `multiclock_captureStmt ) measure_out_sig('d`bist_we, cur_stmt); 
     end
     forever @(ALLOUTSIGS['d`\bist_addr[3] ]) begin
       #0 if (cur_stmt == `VectorStmt || cur_stmt == `multiclock_captureStmt ) measure_out_sig('d`\bist_addr[3] , cur_stmt); 
     end
     forever @(ALLOUTSIGS['d`\bist_addr[2] ]) begin
       #0 if (cur_stmt == `VectorStmt || cur_stmt == `multiclock_captureStmt ) measure_out_sig('d`\bist_addr[2] , cur_stmt); 
     end
     forever @(ALLOUTSIGS['d`\bist_addr[1] ]) begin
       #0 if (cur_stmt == `VectorStmt || cur_stmt == `multiclock_captureStmt ) measure_out_sig('d`\bist_addr[1] , cur_stmt); 
     end
     forever @(ALLOUTSIGS['d`\bist_addr[0] ]) begin
       #0 if (cur_stmt == `VectorStmt || cur_stmt == `multiclock_captureStmt ) measure_out_sig('d`\bist_addr[0] , cur_stmt); 
     end
     forever @(ALLOUTSIGS['d`\bist_pat[1] ]) begin
       #0 if (cur_stmt == `VectorStmt || cur_stmt == `load_unloadStmt || cur_stmt == `multiclock_captureStmt )
       if (cur_stmt ==`load_unloadStmt) measure_scan_out('d`\bist_pat[1] , 0); 
       else measure_out_sig('d`\bist_pat[1] , cur_stmt); 
     end
     forever @(ALLOUTSIGS['d`\bist_pat[0] ]) begin
       #0 if (cur_stmt == `VectorStmt || cur_stmt == `multiclock_captureStmt ) measure_out_sig('d`\bist_pat[0] , cur_stmt); 
     end
     forever @(ALLOUTSIGS['d`bist_done]) begin
       #0 if (cur_stmt == `VectorStmt || cur_stmt == `multiclock_captureStmt ) measure_out_sig('d`bist_done, cur_stmt); 
     end
     forever @(ALLOUTSIGS['d`pass_or_fail]) begin
       #0 if (cur_stmt == `VectorStmt || cur_stmt == `multiclock_captureStmt ) measure_out_sig('d`pass_or_fail, cur_stmt); 
     end
    join
   end 

   task undef_wfc;
     input reg [1:0] wfc;
     input reg [4:0] sid;
     input integer wftid;
   begin
     $display("XTB Error: unrecognized %s value (WFC):%0b, on signal %0s for WFT %0s. Exiting...", wfc[1]?"strobe":"force", wfc[0], SignalIDName[sid], WFTIDName[wftid]);
     $finish;
   end
   endtask

   task apply__multiclock_capture_WFT_WFT;
     reg [SIG_IDS_W-1:0] sid;
     reg [SIG_IDS_W-1:0] n;
     reg [SIG_IDS-1:0] s;
   begin
     for (sid=0; sid < SIG_IDS; sid=sid+1) begin
       n=0; 
       case(sid)
         'd4, 'd3, 'd2, 'd5, 'd6: // \bist_resp[0] , \bist_resp[1] , bist_start, test_si, test_se_con
         begin
           if (ALLINSIGIDS[sid]==1'b1) begin
             for (n=0; n <SignalIDWidth[sid]; n=n+1) begin
               case ({TMPINSIGS_T[MAX_SIGW*sid+n],TMPINSIGS_V[MAX_SIGW*sid+n]})
                 2'b00: begin    ALLINSIGS[MAX_SIGW*sid+n] <=    #(0) 1'b0;   end
                 2'b01: begin    ALLINSIGS[MAX_SIGW*sid+n] <=    #(0) 1'b1;   end
                 2'b0Z: begin    ALLINSIGS[MAX_SIGW*sid+n] <=    #(0) 1'bZ;   end
                 2'b0X: begin    ALLINSIGS[MAX_SIGW*sid+n] <=    #(0) 1'bX;   end
                 default: undef_wfc({TMPINSIGS_T[MAX_SIGW*sid+n],TMPINSIGS_V[MAX_SIGW*sid+n]}, sid, 0);
               endcase
             end
           end
         end 
         'd12, 'd11, 'd10, 'd9, 'd7, 'd15, 'd14, 'd13, 'd8, 'd16: // \bist_addr[0] , \bist_addr[1] , \bist_addr[2] , \bist_addr[3] , bist_cs, bist_done, \bist_pat[0] , \bist_pat[1] , bist_we, pass_or_fail_con
         begin
           if (ALLOUTSIGIDS[sid]==1'b1) begin
             for (n=0; n <SignalIDWidth[sid]; n=n+1) begin
               case ({TMPOUTSIGS_T[MAX_SIGW*sid+n],TMPOUTSIGS_V[MAX_SIGW*sid+n]})
                 2'b1X: begin 
                         ALLOUTSIGS[MAX_SIGW*sid+n] <=    #(0) 1'bX;
                         ALLOUTSIGS[MAX_SIGW*sid+n] <=    #(40) 1'bX;   end
                 2'b11: begin 
                         ALLOUTSIGS[MAX_SIGW*sid+n] <=    #(0) 1'bX;
                         ALLOUTSIGS[MAX_SIGW*sid+n] <=    #(40) 1'b1;   end
                 2'b10: begin 
                         ALLOUTSIGS[MAX_SIGW*sid+n] <=    #(0) 1'bX;
                         ALLOUTSIGS[MAX_SIGW*sid+n] <=    #(40) 1'b0;   end
                 2'b1Z: begin 
                         ALLOUTSIGS[MAX_SIGW*sid+n] <=    #(0) 1'bX;
                         ALLOUTSIGS[MAX_SIGW*sid+n] <=    #(40) 1'bZ;   end
                 default: undef_wfc({TMPOUTSIGS_T[MAX_SIGW*sid+n],TMPOUTSIGS_V[MAX_SIGW*sid+n]}, sid, 0);
               endcase
             end
           end
         end 
         'd0: // clk
         begin
           if (ALLINSIGIDS[sid]==1'b1) begin
             for (n=0; n <SignalIDWidth[sid]; n=n+1) begin
               case ({TMPINSIGS_T[MAX_SIGW*sid+n],TMPINSIGS_V[MAX_SIGW*sid+n]})
                 2'b00: begin    ALLINSIGS[MAX_SIGW*sid+n] <=    #(0) 1'b0;   end
                 2'b01: begin    ALLINSIGS[MAX_SIGW*sid+n] <=    #(0) 1'b1;   end
                 2'b0Z: begin    ALLINSIGS[MAX_SIGW*sid+n] <=    #(0) 1'bZ;   end
                 2'b0X: begin    ALLINSIGS[MAX_SIGW*sid+n] <=    #(0) 1'bX;   end
                 2'bZ1: begin    ALLINSIGS[MAX_SIGW*sid+n] <=    #(0) 1'b0;   ALLINSIGS[MAX_SIGW*sid+n] <=    #(45) 1'b1;   ALLINSIGS[MAX_SIGW*sid+n] <=    #(55) 1'b0;   end
                 default: undef_wfc({TMPINSIGS_T[MAX_SIGW*sid+n],TMPINSIGS_V[MAX_SIGW*sid+n]}, sid, 0);
               endcase
             end
           end
         end 
         'd1: // rst_n
         begin
           if (ALLINSIGIDS[sid]==1'b1) begin
             for (n=0; n <SignalIDWidth[sid]; n=n+1) begin
               case ({TMPINSIGS_T[MAX_SIGW*sid+n],TMPINSIGS_V[MAX_SIGW*sid+n]})
                 2'b00: begin    ALLINSIGS[MAX_SIGW*sid+n] <=    #(0) 1'b0;   end
                 2'b01: begin    ALLINSIGS[MAX_SIGW*sid+n] <=    #(0) 1'b1;   end
                 2'b0Z: begin    ALLINSIGS[MAX_SIGW*sid+n] <=    #(0) 1'bZ;   end
                 2'b0X: begin    ALLINSIGS[MAX_SIGW*sid+n] <=    #(0) 1'bX;   end
                 2'bZ1: begin    ALLINSIGS[MAX_SIGW*sid+n] <=    #(0) 1'b1;   ALLINSIGS[MAX_SIGW*sid+n] <=    #(45) 1'b0;   ALLINSIGS[MAX_SIGW*sid+n] <=    #(55) 1'b1;   end
                 default: undef_wfc({TMPINSIGS_T[MAX_SIGW*sid+n],TMPINSIGS_V[MAX_SIGW*sid+n]}, sid, 0);
               endcase
             end
           end
         end 
       endcase 
     end 
   end 
   endtask

   task apply__default_WFT_WFT;
     reg [SIG_IDS_W-1:0] sid;
     reg [SIG_IDS_W-1:0] n;
     reg [SIG_IDS-1:0] s;
   begin
     for (sid=0; sid < SIG_IDS; sid=sid+1) begin
       n=0; 
       case(sid)
         'd4, 'd3, 'd2, 'd5, 'd6: // \bist_resp[0] , \bist_resp[1] , bist_start, test_si, test_se_con
         begin
           if (ALLINSIGIDS[sid]==1'b1) begin
             for (n=0; n <SignalIDWidth[sid]; n=n+1) begin
               case ({TMPINSIGS_T[MAX_SIGW*sid+n],TMPINSIGS_V[MAX_SIGW*sid+n]})
                 2'b00: begin    ALLINSIGS[MAX_SIGW*sid+n] <=    #(0) 1'b0;   end
                 2'b01: begin    ALLINSIGS[MAX_SIGW*sid+n] <=    #(0) 1'b1;   end
                 2'b0Z: begin    ALLINSIGS[MAX_SIGW*sid+n] <=    #(0) 1'bZ;   end
                 2'b0X: begin    ALLINSIGS[MAX_SIGW*sid+n] <=    #(0) 1'bX;   end
                 default: undef_wfc({TMPINSIGS_T[MAX_SIGW*sid+n],TMPINSIGS_V[MAX_SIGW*sid+n]}, sid, 1);
               endcase
             end
           end
         end 
         'd12, 'd11, 'd10, 'd9, 'd7, 'd15, 'd14, 'd13, 'd8, 'd16: // \bist_addr[0] , \bist_addr[1] , \bist_addr[2] , \bist_addr[3] , bist_cs, bist_done, \bist_pat[0] , \bist_pat[1] , bist_we, pass_or_fail_con
         begin
           if (ALLOUTSIGIDS[sid]==1'b1) begin
             for (n=0; n <SignalIDWidth[sid]; n=n+1) begin
               case ({TMPOUTSIGS_T[MAX_SIGW*sid+n],TMPOUTSIGS_V[MAX_SIGW*sid+n]})
                 2'b1X: begin 
                         ALLOUTSIGS[MAX_SIGW*sid+n] <=    #(0) 1'bX;
                         ALLOUTSIGS[MAX_SIGW*sid+n] <=    #(40) 1'bX;   end
                 2'b11: begin 
                         ALLOUTSIGS[MAX_SIGW*sid+n] <=    #(0) 1'bX;
                         ALLOUTSIGS[MAX_SIGW*sid+n] <=    #(40) 1'b1;   end
                 2'b10: begin 
                         ALLOUTSIGS[MAX_SIGW*sid+n] <=    #(0) 1'bX;
                         ALLOUTSIGS[MAX_SIGW*sid+n] <=    #(40) 1'b0;   end
                 2'b1Z: begin 
                         ALLOUTSIGS[MAX_SIGW*sid+n] <=    #(0) 1'bX;
                         ALLOUTSIGS[MAX_SIGW*sid+n] <=    #(40) 1'bZ;   end
                 default: undef_wfc({TMPOUTSIGS_T[MAX_SIGW*sid+n],TMPOUTSIGS_V[MAX_SIGW*sid+n]}, sid, 1);
               endcase
             end
           end
         end 
         'd0: // clk
         begin
           if (ALLINSIGIDS[sid]==1'b1) begin
             for (n=0; n <SignalIDWidth[sid]; n=n+1) begin
               case ({TMPINSIGS_T[MAX_SIGW*sid+n],TMPINSIGS_V[MAX_SIGW*sid+n]})
                 2'b00: begin    ALLINSIGS[MAX_SIGW*sid+n] <=    #(0) 1'b0;   end
                 2'b01: begin    ALLINSIGS[MAX_SIGW*sid+n] <=    #(0) 1'b1;   end
                 2'b0Z: begin    ALLINSIGS[MAX_SIGW*sid+n] <=    #(0) 1'bZ;   end
                 2'b0X: begin    ALLINSIGS[MAX_SIGW*sid+n] <=    #(0) 1'bX;   end
                 2'bZ1: begin    ALLINSIGS[MAX_SIGW*sid+n] <=    #(0) 1'b0;   ALLINSIGS[MAX_SIGW*sid+n] <=    #(45) 1'b1;   ALLINSIGS[MAX_SIGW*sid+n] <=    #(55) 1'b0;   end
                 default: undef_wfc({TMPINSIGS_T[MAX_SIGW*sid+n],TMPINSIGS_V[MAX_SIGW*sid+n]}, sid, 1);
               endcase
             end
           end
         end 
         'd1: // rst_n
         begin
           if (ALLINSIGIDS[sid]==1'b1) begin
             for (n=0; n <SignalIDWidth[sid]; n=n+1) begin
               case ({TMPINSIGS_T[MAX_SIGW*sid+n],TMPINSIGS_V[MAX_SIGW*sid+n]})
                 2'b00: begin    ALLINSIGS[MAX_SIGW*sid+n] <=    #(0) 1'b0;   end
                 2'b01: begin    ALLINSIGS[MAX_SIGW*sid+n] <=    #(0) 1'b1;   end
                 2'b0Z: begin    ALLINSIGS[MAX_SIGW*sid+n] <=    #(0) 1'bZ;   end
                 2'b0X: begin    ALLINSIGS[MAX_SIGW*sid+n] <=    #(0) 1'bX;   end
                 2'bZ1: begin    ALLINSIGS[MAX_SIGW*sid+n] <=    #(0) 1'b1;   ALLINSIGS[MAX_SIGW*sid+n] <=    #(45) 1'b0;   ALLINSIGS[MAX_SIGW*sid+n] <=    #(55) 1'b1;   end
                 default: undef_wfc({TMPINSIGS_T[MAX_SIGW*sid+n],TMPINSIGS_V[MAX_SIGW*sid+n]}, sid, 1);
               endcase
             end
           end
         end 
       endcase 
     end 
   end 
   endtask

   task resolve_wft;
     input integer wftid ;
   begin
     if (wftid > WFT_IDS || wftid <0) begin 
       $display("\nXTB Error: undefined WFT id %0d (valid range is 0..%0d). Exiting...",wftid, WFT_IDS);
       $finish;
     end
     the_wft_id = wftid;
   end
   endtask

   task apply_wft; 
     input integer wftid ;
   begin
     case (wftid) 
       'd0: apply__multiclock_capture_WFT_WFT;
       'd1: apply__default_WFT_WFT;
       default:begin $display("\nXTB Error: undefined WFT id %d. Exiting...",wftid); $finish; end
     endcase
   end
   endtask 

   task complete_cycle;
     input integer wft_id ;
   begin
     case(wft_id)
       'd0: #(100); // _multiclock_capture_WFT_
       'd1: #(100); // _default_WFT_
     endcase
   end
   endtask

   task set_args;
     input reg [4:0] nargs;
     integer i, na;
     reg [2*CUM_WIDTH-1:0] sidx;
     reg [SIG_IDS_W-1:0] sid; 
   begin
     na = 0; sid_args = 'b0; sval_args = 'b0;
     while (na < nargs) begin
       data_i = data_i + 1;
       memel = memall[data_i];
       sid = memel[SIG_IDS_W-1:0];
       if (sid > SIG_IDS-1) begin
         $display($time, "\nXTB Error: Passing wrong signal ID (%0b), valid range is 1..%0d. Exiting...", sid, SIG_IDS-1);
         $finish; 
       end
       sid_args[sid] = 1'b1;
       sidx = sig_idx(sid);
       for (i = 0; i < 2*SignalIDWidth[sid]; i = i + 1)
         sval_args[sidx+i] = memel[i+SIG_IDS_W];
       na=na+1; 
    end  
  end 
  endtask

   function [2*CUM_WIDTH-1:0] sig_idx;
     input reg [SIG_IDS_W-1:0] sid;
     integer i; 
   begin
     sig_idx = 0;
     for (i = 0; i < sid; i = i + 1)  sig_idx = sig_idx+2*SignalIDWidth[i]; 
   end 
   endfunction

   task  assign_ival;
     input reg [SIG_IDS_W-1:0] sid;
     reg [2*CUM_WIDTH-1:0] sidx;
     reg [2*MAX_WIDTH-1:0] sval;
     integer i;
   begin 
     sidx = sig_idx(sid);
     for (i = 0; i<2*SignalIDWidth[sid]; i = i + 1) sval[i] = sval_args[sidx+i];
     assign_val(sid , sval);
   end 
   endtask

   task  assign_val;
     input reg [SIG_IDS_W-1:0] sid;
     input reg [2*MAX_WIDTH-1:0] sval;
     reg [MAX_WIDTH-1:0] nb; 
     reg [6:0] idx;
     integer n, ns;
   begin
     if (sid > SIG_IDS-1 || sid < 0) begin
       $display("\nXTB Error: Passing wrong signal ID (%d), valid range is 1..%0d. Exiting...", sid, SIG_IDS-1);
       $finish;
     end
     resolve_signal(sid);
     idx = 0; 
     ns = (SignalIDType[sid]==3) ? SignalIDWidth[sid] : 1;
     for (n = 0; n < ns; n = n + 1)
     begin
       if (sval[idx+SignalIDWidth[sid]] === 1'b1) begin
         for (nb = 0; nb < SignalIDWidth[the_sids[n]]; nb = nb + 1) begin
           TMPOUTSIGS_V[MAX_SIGW*the_sids[n]+nb]  = sval[idx+nb];
           TMPOUTSIGS_T[MAX_SIGW*the_sids[n]+nb]  = sval[idx+nb+SignalIDWidth[sid]];
           ALLOUTSIGIDS[the_sids[n]] = 1'b1; 
           if (sval[idx+nb] !== 1'bx)
             ALLINSIGIDS[the_sids[n]] = 1'b0;
         end
       end
       else begin
         for (nb = 0; nb < SignalIDWidth[the_sids[n]]; nb = nb + 1) begin
           TMPINSIGS_V[MAX_SIGW*the_sids[n]+nb]  = sval[idx+nb];
           TMPINSIGS_T[MAX_SIGW*the_sids[n]+nb]  = sval[idx+nb+SignalIDWidth[sid]];
           ALLINSIGIDS[the_sids[n]] = 1'b1;
           ALLOUTSIGIDS[the_sids[n]] = 1'b0;
       end 
     end
     idx = idx+SignalIDWidth[the_sids[n]];
     end 
   end 
   endtask

   task  check_sid_args;
     input reg [(NAMELENGTH-1):0] tname;
     input reg [SIG_IDS-1:0] vargs ;
     input reg [SIG_IDS-1:0] cargs ;
     integer i;
   begin
     for (i = 0; i < SIG_IDS-1; i = i + 1)
       if (cargs[i] === 1'b1 && vargs[i] !== 1'b1) begin
         $display("\nXTB Error: Passing wrong signal argument (%s), to Macro/Procedure %s. Exiting...", SignalIDName[i], tname); 
         $finish;
       end 
   end 
   endtask

   task  assign_stmt;
     input integer wftid ;
   begin
     v_count = v_count+1;
     v_count_per_pat = v_count_per_pat+1;
     if (verbose >= 4) $display("XTB: Starting V# %0d at time %0t", v_count, $time);
     apply_wft(wftid);
     complete_cycle(wftid);
   end
   endtask

   task display_stmt;
     input integer stmtid;
   begin
     $display("XTB: Processed statement: %0s", StmtNames[stmtid]);
   end
   endtask

   task read_data;
     integer tdf;
   begin
     tdf = $fopen(TDATA_FILE, "r");
     if (!tdf) begin 
       $display("XTB Error: cannot open %0s file. Exiting...\n", TDATA_FILE);
       $finish; 
      end 
      $fclose(tdf); 
     if (tdfm > 0) $display("XTB: Setting test data file to \"%0s\" (at %0s). Running simulation with new database...", TDATA_FILE, tdfm==1?"compile-time":"runtime");
     else if (verbose >= 1) $display("XTB: Reading test data file \"%0s\" ", TDATA_FILE);
     $readmemb(TDATA_FILE, memall);
   end
    endtask

   task measure_chain_out;
     input reg [NCHAINS-1:0] chid;
     integer bi, errshown, patoff, prefo;
     integer tsc;
     reg [0:MAXCHLEN-1] UNLM;
   begin
     tsc = 0;
     prefo = 0;
     UNLM = ~('b0);
     CHAINOUT[0] = (CHAINOUT0);
     UNL = UNLOAD[chid] << prefo;
     CHOUT = CHAINOUT[chid] ^ CH_OUTINV[chid];

     for (bi = 0; bi < MAXCHLEN; bi = bi + 1)
       if (UNL[bi] === 1'bx) UNLM[bi] = 1'b0;

     for (bi = 0; bi < prefo; bi = bi + 1) UNLM[MAXCHLEN-1-bi] = 1'b0;

     if ((UNL&UNLM) !== (CHOUT&UNLM)) begin
       patoff = (loads > 1 || cur_pat <= 0) ? 0 : 1;
     if (cur_pat <= 0 || cur_pat == last_pat && loads > 1) begin
       $display(">>>  Error during scan pattern %0d %s", (cur_pat<0)?0:cur_pat, (cur_pat==last_pat)?"(detected from final parallel pattern unload)":"");
     end
     else begin
       if (loads > 1) $display(">>>  Error during scan pattern %0d (detected from %0d parallel load/unload)", cur_pat, loads);
       else begin $display(">>>  Error during scan pattern %0d (detected from parallel unload of pattern %0d)", cur_pat, cur_pat-1); end
     end
       for (bi = 0; bi < MAXCHLEN-prefo; bi=bi + 1) begin
         if ((UNL[bi] !== 1'bx) && (UNL[bi] !== CHOUT[bi])) begin
           $display(">>>  \tAt T=%0t, V=%0d, exp=%b, got=%b, chain %0s, pin %0s, scan cell %0d", $time, sertmg?v_count+1+bi+prefo:v_count, UNL[bi], CHOUT[bi], CH_NAMES[chid], CH_PINS[chid], bi+prefo+tsc);
           if (diagf) begin 
           if (diagm==2) $fdisplay(diagf, "  C %0s %0d (exp=%b, got=%b) ", CH_PINS[chid], v_count, UNL[bi], CHOUT[bi]);
           else $fdisplay(diagf, "  %0d %0s %0d (exp=%b, got=%b)",
               cur_pat-patoff, CH_PINS[chid], bi+prefo+tsc, UNL[bi], CHOUT[bi]);
           end 
           nbfails = nbfails + 1;
          end 
       end  
     end
   end 
   endtask

   task test_setup ;
     input reg [SIG_IDS-1:0] idargs;
     input reg [2*CUM_WIDTH-1:0] valargs;
   begin
     if (test_setup_only_once > 0 && test_setup_runs > 0) begin
       if (verbose >= 2) $display("XTB: Skipping macro test_setup...");
       disable test_setup;
     end
     test_setup_runs = test_setup_runs + 1;
     if (verbose >= 2) $display("XTB: Starting macro test_setup..., T=%0t, V=%0d", $time, v_count+1);
     //check_sid_args("test_setup",24'b1, idargs);
     resolve_wft(1);

     assign_val('d`all_inputs , 14'b0000000XXXXXXX);
     assign_val('d`all_outputs , 20'b1111111111XXXXXXXXXX);

     assign_val('d`clk , 2'b00);
     assign_val('d`rst_n , 2'b01);
     assign_stmt(the_wft_id);

     assign_stmt(the_wft_id);

   end 
   endtask

   task shift_0 ;
     input reg [SIG_IDS-1:0] idargs;
     input reg [2*CUM_WIDTH-1:0] valargs;
     input integer stsci;
     input reg stroben;
   begin
    csci = stsci+0; prev_error = -2;
    while (csci < 21) begin
     fsci = csci;
     if (verbose >= 2) $display("XTB: shift %0d, at %0t ", csci, $time);
     resolve_wft(1);
     assign_val('d`_clk , 4'bZ011);
         if (idargs[20] === 1'b1 || idargs[5] === 1'b1) begin 
           LOD=LOAD[0]; assign_val('d`test_si , {1'b0, LOD[csci+0]});
         end
         if(stroben && (idargs[23] === 1'b1 || idargs[13] === 1'b1)) begin 
           UNL = UNLOAD[0]; assign_val('d`\bist_pat[1]  , {1'b1,  UNL[csci+0]});
         end
     assign_stmt(the_wft_id);
     csci = csci+1;
    end
   end
   endtask


   always /* ParallelShiftMode */ @(strobe_scells) begin
     CHAINOUT0[0:20] = {`XTB_DUT_HIER.bist_pat[1] , `XTB_DUT_HIER.i_bist_pat_gen.bist_pat_reg_reg_1_.SI , `XTB_DUT_HIER.i_bist_pat_gen.bist_pat_reg_reg_0_.SI , `XTB_DUT_HIER.i_bist_controller.state_reg_2_.SI , `XTB_DUT_HIER.i_bist_controller.state_reg_1_.SI , `XTB_DUT_HIER.i_bist_controller.state_reg_0_.SI , `XTB_DUT_HIER.i_bist_controller.bist_we_reg_reg.SI , `XTB_DUT_HIER.i_bist_controller.bist_done_reg_reg.SI , `XTB_DUT_HIER.i_bist_controller.bist_cs_reg_reg.SI , `XTB_DUT_HIER.i_bist_cmp.pass_or_fail_reg_reg.SI , `XTB_DUT_HIER.i_bist_buf.we_buf_1_reg.SI , `XTB_DUT_HIER.i_bist_buf.pat_buf_1_reg_1_.SI , `XTB_DUT_HIER.i_bist_buf.pat_buf_1_reg_0_.SI , `XTB_DUT_HIER.i_bist_buf.cs_buf_1_reg.SI , `XTB_DUT_HIER.i_bist_addr_gen.bist_addr_reg_reg_3_.SI , `XTB_DUT_HIER.i_bist_addr_gen.bist_addr_reg_reg_2_.SI , `XTB_DUT_HIER.i_bist_addr_gen.bist_addr_reg_reg_1_.SI , `XTB_DUT_HIER.i_bist_addr_gen.bist_addr_reg_reg_0_.SI , `XTB_DUT_HIER.i_bist_addr_gen.addr_cnt_reg_3_.SI , `XTB_DUT_HIER.i_bist_addr_gen.addr_cnt_reg_2_.SI , `XTB_DUT_HIER.i_bist_addr_gen.addr_cnt_reg_1_.SI };
   end

   `define CELL0IN0 `XTB_DUT_HIER.i_bist_addr_gen.addr_cnt_reg_0_.SI
   `define CHAININ0 {`XTB_DUT_HIER.i_bist_pat_gen.bist_pat_reg_reg_1_.SI , `XTB_DUT_HIER.i_bist_pat_gen.bist_pat_reg_reg_0_.SI , `XTB_DUT_HIER.i_bist_controller.state_reg_2_.SI , `XTB_DUT_HIER.i_bist_controller.state_reg_1_.SI , `XTB_DUT_HIER.i_bist_controller.state_reg_0_.SI , `XTB_DUT_HIER.i_bist_controller.bist_we_reg_reg.SI , `XTB_DUT_HIER.i_bist_controller.bist_done_reg_reg.SI , `XTB_DUT_HIER.i_bist_controller.bist_cs_reg_reg.SI , `XTB_DUT_HIER.i_bist_cmp.pass_or_fail_reg_reg.SI , `XTB_DUT_HIER.i_bist_buf.we_buf_1_reg.SI , `XTB_DUT_HIER.i_bist_buf.pat_buf_1_reg_1_.SI , `XTB_DUT_HIER.i_bist_buf.pat_buf_1_reg_0_.SI , `XTB_DUT_HIER.i_bist_buf.cs_buf_1_reg.SI , `XTB_DUT_HIER.i_bist_addr_gen.bist_addr_reg_reg_3_.SI , `XTB_DUT_HIER.i_bist_addr_gen.bist_addr_reg_reg_2_.SI , `XTB_DUT_HIER.i_bist_addr_gen.bist_addr_reg_reg_1_.SI , `XTB_DUT_HIER.i_bist_addr_gen.bist_addr_reg_reg_0_.SI , `XTB_DUT_HIER.i_bist_addr_gen.addr_cnt_reg_3_.SI , `XTB_DUT_HIER.i_bist_addr_gen.addr_cnt_reg_2_.SI , `XTB_DUT_HIER.i_bist_addr_gen.addr_cnt_reg_1_.SI ,  `CELL0IN0 }


   task p_shift_0 ;
     input reg [SIG_IDS-1:0] idargs;
     input reg [2*CUM_WIDTH-1:0] valargs;
     integer i, j;
   begin
     if (~(idargs[20] | idargs[5] | idargs[23] | idargs[13] )) 
       disable p_shift_0 ; 
     if (SSHIFTS < MAXCHLEN) begin
         if (verbose >= 2) $display("XTB: (parallel) shift, at %0t  ", $time);
         resolve_wft(1);
     fork 
       begin: b1 
         #40 ;
         -> strobe_scells;
         repeat (SYNC_LATENCY) #0;
         if (idargs[23] === 1'b1 ||  idargs[13] === 1'b1) begin 
           measure_chain_out('d0);
         end
         if (idargs[20] === 1'b1 ||  idargs[5] === 1'b1) begin 
           LOD0=(LOAD[0] >> SSHIFTS) ^ CH_INPINV[0];
         end

           ->force_scells; 
         #0;
       end 
       begin: b2
         assign_val('d`_clk , 4'bZ011);
         assign_stmt(the_wft_id);
       end 
     join 

     ->release_scells; 

         #0;
         if (sertmg == 1) begin
           v_count = v_count + PARSERINC - SSHIFTS - 1;
           for (i = 0; i < PARSERINC - SSHIFTS - 1; i = i+1)
             complete_cycle(the_wft_id);
         end
         if (SSHIFTS > 0) shift_0(idargs, valargs, MAXCHLEN-SSHIFTS, 0) ; 

     end 
     else begin 
         shift_0(idargs, valargs, 0, 1);
     end
   end
   endtask


   always /* ParallelShiftMode */ @(force_scells) begin 
           force `CHAININ0 = LOD0;

   end


   always /* ParallelShiftMode */ @(release_scells) begin 
     release `CHAININ0; 
   end

   task load_unload ;
     input reg [SIG_IDS-1:0] idargs;
     input reg [2*CUM_WIDTH-1:0] valargs;
   begin
     if (verbose >= 2) $display("XTB: Starting proc load_unload..., T=%0t, V=%0d", $time, v_count+1);

     if (xtb_sim_mode == 0 && ser_pats > 0 && cur_pat < last_pat && cur_pat == (ser_pats+first_pat)) begin
       $display("XTB: Switching into Parallel simulation mode at pattern %0d (using %0d serial shifts)", cur_pat, SSHIFTS);
       xtb_sim_mode = 1; 
     end
     if (cur_pat != prev_pat) begin
       loads = 1;
       prev_pat = cur_pat;
       if (cur_pat % rep_pat == 0)
         $display("XTB: Begin %0s scan load for pattern %0d (T=%0t, V=%0d)", xtb_sim_mode?"parallel":"serial", cur_pat, $time, v_count+1);
     end
     else begin
       loads = loads + 1;
       if (cur_pat % rep_pat == 0)
         $display("XTB: Begin %0s scan load for pattern %0d, unload %0d (T=%0t, V=%0d)", xtb_sim_mode?"parallel":"serial", cur_pat, loads, $time, v_count+1);
     end
     save_context;
     resolve_wft(1);

     assign_val('d`all_inputs , 14'b0000000XXX01XX);
     assign_val('d`all_outputs , 20'b1111111111XXXXXXXXXX);

     assign_val('d`test_se , 2'b01);
     assign_stmt(the_wft_id);

     if (xtb_sim_mode)      p_shift_0(idargs, valargs);
     else      shift_0(idargs, valargs, 0, 1);

     restore_context;
   end 
   endtask

   task multiclock_capture ;
     input reg [SIG_IDS-1:0] idargs;
     input reg [2*CUM_WIDTH-1:0] valargs;
   begin
     if (verbose >= 2) $display("XTB: Starting proc multiclock_capture..., T=%0t, V=%0d", $time, v_count+1);
     //check_sid_args("multiclock_capture",24'b1, idargs);
     save_context;
     resolve_wft(0);

     assign_val('d`all_inputs , 14'b0000000XXX01XX);
     assign_val('d`all_outputs , 20'b1111111111XXXXXXXXXX);

     if (idargs[17] === 1'b1) assign_ival('d`_pi );
     if (idargs[4] === 1'b1) assign_ival('d`\bist_resp[0]  );
     if (idargs[3] === 1'b1) assign_ival('d`\bist_resp[1]  );
     if (idargs[2] === 1'b1) assign_ival('d`bist_start );
     if (idargs[0] === 1'b1) assign_ival('d`clk );
     if (idargs[1] === 1'b1) assign_ival('d`rst_n );
     if (idargs[5] === 1'b1) assign_ival('d`test_si );
     if (idargs[6] === 1'b1) assign_ival('d`test_se );
     if (idargs[19] === 1'b1) assign_ival('d`_po );
     if (idargs[12] === 1'b1) assign_ival('d`\bist_addr[0]  );
     if (idargs[11] === 1'b1) assign_ival('d`\bist_addr[1]  );
     if (idargs[10] === 1'b1) assign_ival('d`\bist_addr[2]  );
     if (idargs[9] === 1'b1) assign_ival('d`\bist_addr[3]  );
     if (idargs[7] === 1'b1) assign_ival('d`bist_cs );
     if (idargs[15] === 1'b1) assign_ival('d`bist_done );
     if (idargs[14] === 1'b1) assign_ival('d`\bist_pat[0]  );
     if (idargs[13] === 1'b1) assign_ival('d`\bist_pat[1]  );
     if (idargs[8] === 1'b1) assign_ival('d`bist_we );
     if (idargs[16] === 1'b1) assign_ival('d`pass_or_fail );
     assign_stmt(the_wft_id);

     restore_context;
   end 
   endtask


   always @(start_part) begin: _burst__pattern__proc_unit

     integer nbpats, i;
     integer nargs, na;
     integer args;

     integer tdf;
     nbpats = 0; cur_pat = -1;
     end_pat = 0; v_count = 0; v_count_per_pat = 0;
     nbfails = 0;
     prev_pat = -2; prev_error = -2; first_pat = 0;
     diagf = 0;
     read_data;
     data_i = 1; 
     popcode = 'd0;

     if (diagm > 0) begin
       if (diagm > 2) begin
         $display("XTB Warning: wrong diagnosis mode (%0d), using default mode 1 (pattern based)", diagm);
         diagm = 1 ; 
       end  
       `ifdef tmax_diag_file 
         diag_file = `tmax_diag_file;
       `else 
         diag_file = "top_dft_tb.diag"; 
       `endif
       diagf = $fopen(diag_file);
       if (diagf == 0) begin
         $display("XTB Error: Unable to open diagnosis file %s (for writing). Exiting...", diag_file);
         $finish; 
       end
       if (verbose >= 1) $display("XTB: User requesting TetraMAX compliant diagnosis file: %0s", diag_file);
       $fdisplay(diagf, "// Serial scan error:       <pat#> \t<pin_name> \t<shift_index> \t(<expected_value> <simulated_value>)");
       $fdisplay(diagf, "// USF Parallel scan error: <pat#> \t<pin_name> \t<shift_index> \t(<expected_value> <simulated_value>)");
       $fdisplay(diagf, "// DSF Parallel scan error: <pat#> \t<chain_name> \t<cell_index> \t(<expected_value> <simulated_value>)");
       $fdisplay(diagf, "// Capture error:           <pat#> \t<pin_name> \t(<expected_value> <simulated_value>)");
       $fdisplay(diagf, "// Cycle based error:          C \t<pin_name> \t<vect_nbr> \t(<expected_value> <simulated_value>)\n\n");

     end 

     memel = memall[data_i]; 
     total_pats = memel[31:0];
     data_i=data_i+1;

     last_pat = -1;

     if (total_pats < 0 || |(total_pats) === 1'bx) begin
       $display("XTB Error: Inconsistent total number of patterns (%d). Exiting...",  total_pats);
       $finish;
     end

     if (verbose >= 1) $display("XTB: Total number of patterns  %0d",  total_pats); 
     if (last_pat == -1) last_pat = total_pats - 1;

     `ifdef tmax_n_pattern_sim
     last_pat=`tmax_n_pattern_sim;
     `endif

     `ifdef tmax_test_setup_only_once
     test_setup_only_once = 1;
     `endif

     xtb_sim_mode = 1;
     SSHIFTS = DFSHIFTS;

     ser_pats = 0;
     csim_op = -1;

     `ifdef tmax_serial
       if (~(`tmax_serial & 1'b1) == 1'b0) 
         ser_pats = last_pat + 1;
       else 
         ser_pats = `tmax_serial + 0;
       if (ser_pats > 0)
       csim_op = 0;
       `ifdef tmax_parallel 
         if (~(`tmax_parallel & 1'b1) == 1'b0) SSHIFTS = DFSHIFTS;
         else SSHIFTS = `tmax_parallel + 0; 
         if (ser_pats  >= last_pat + 1) begin	 
           csim_op = 2; 
         end 
         else if (ser_pats == 0)
           csim_op = 1;
       `endif
     `else 
       `ifdef tmax_parallel
         csim_op = 1;
         if (~(`tmax_parallel & 1'b1) == 1'b0) SSHIFTS = DFSHIFTS;
         else SSHIFTS = `tmax_parallel + 0; 
       `endif 
     `endif
     if (SSHIFTS < 0) begin
       $display("XTB Error: Passing negative value (%0d) of serial shifts in parallel mode. Exiting...",  SSHIFTS);
       $finish; 
     end

     process_rtops;
     `ifdef tmax_serial_timing 
       sertmg = 1;
       if (xtb_sim_mode == 1) $display("XTB: Parallel simulation (timing and vector) extended to match serial simulation");
     `else 
       sertmg = 0; 
     `endif


     $display("XTB: Starting %0s simulation of %0d pattern%s", xtb_sim_mode == 0 ? "serial" : "parallel", xtb_sim_mode == 0 ? ((ser_pats>last_pat || ser_pats==0)?(last_pat+1):ser_pats): last_pat + 1, (xtb_sim_mode!=0 || ser_pats>1)?"s":"");
     if (xtb_sim_mode) begin 
       $display("XTB: Using %0d serial shifts", SSHIFTS);
     end

     if (SSHIFTS >= MAXCHLEN)  begin 
       $display("XTB Warning: serial shifts (%0d) equals or exceeds max chain length (%0d). Performing full serial scan... ", SSHIFTS, MAXCHLEN); 
       xtb_sim_mode = 0;	
     end 

     if (diagm==2 && xtb_sim_mode==1)  begin 
       $display("XTB Warning: cannot display cycle-based diagnostic messages in parallel load mode simulation. Simulation will display pattern-based diagnostic messages."); 
       diagm = 1;	
     end 

     while (cur_pat <= last_pat && end_pat != 1) begin 
       memel = memall[data_i];
       opcode = memel[15:0];
       cur_stmt = -1;
       args = 'b0;
       case (opcode)
         'd`EndPat:  begin
                       cur_stmt = `EndPat;
                       end_pat = 1;
                     end
         'd`IncPat:  begin
                       cur_stmt = `IncPat;
                       cur_pat = cur_pat + 1;
                       v_count_per_pat = 0;
                       nbpats = nbpats+1;

                     end
         'd`SetValidStrobe:  begin
                       cur_stmt = `SetValidStrobe;
                     end
         'd`SetForceSI:  begin
                       cur_stmt = `SetForceSI;
                     end
         'd`SetPat:  begin
                       cur_stmt = `SetPat;
                       v_count_per_pat = 0;
                       if (cur_pat==-1) begin first_pat = memel[43:16]; cur_pat = first_pat; end
                       else cur_pat = memel[43:16];
                       last_pat = last_pat + cur_pat; 
                       nbpats = nbpats+1;  
                     end
         'd`WFTStmt: begin
                       cur_stmt = `WFTStmt;
                       resolve_wft(memel[17:16]);
                     end 
         'd`ConditionStmt, 'd`FixedStmt, 'd`VectorStmt: begin
           if (opcode == 'd`ConditionStmt) cur_stmt = 'd`ConditionStmt;
           else 	cur_stmt='d`VectorStmt;
           nargs = memel[20:16];
           na = 0;
           while (na<nargs) begin
             data_i = data_i + 1;
             memel = memall[data_i];
             assign_val(memel[SIG_IDS_W-1:0], memel[2*MAX_WIDTH+SIG_IDS_W-1:SIG_IDS_W]);
             na = na + 1;
           end
           if (opcode == `VectorStmt) assign_stmt(the_wft_id);
          end 
          'd`GenLoopStmt: begin: GenLoop_BLOCK
            cur_stmt = `GenLoopStmt;
            lp_count = 1;
            lp_addr = data_i;
            lp_max = memel[31:16];
            $display("\nXTB: starting loop statement with %0d iterations", lp_max); 
          end 
          'd`EndGenLoopStmt: begin: EndLoop_BLOCK
            cur_stmt = `EndGenLoopStmt;
            $display("\nXTB: loop iteration %0d/%0d done.", lp_count, lp_max);
            lp_count = lp_count+1;
            if (lp_count <= lp_max) begin
              data_i = lp_addr;
            end 
         end 
         'd`test_setupStmt: begin: test_setup_BLOCK
           cur_stmt = `test_setupStmt;
           set_args(memel[20:16]);
             test_setup(sid_args, sval_args);
         end 
         'd`load_unloadStmt: begin: load_unload_BLOCK
           cur_stmt = `load_unloadStmt;
            na = 0; nargs = 'b0; sid_args = 'b0; sval_args = 'b0;
            nargs = memel[20:16];
            while (na < nargs) begin
              data_i = data_i + 1;
              memel = memall[data_i];
              if (memel[SIG_IDS_W-1:0] > SIG_IDS-1) begin
                $display("\nXTB Error: Passing wrong signal ID (%b), valid range is 1..%d. Exiting...", memel[SIG_IDS_W-1:0], SIG_IDS-1);
                $finish;
              end
              sid_args[memel[SIG_IDS_W-1:0]] = 1'b1;
              case (memel[SIG_IDS_W-1:0])
               'd`_si , 'd`test_si: begin LOAD[0] = memel[MAXCHLEN-1+SIG_IDS_W:SIG_IDS_W]; end 
               'd`_so , 'd`\bist_pat[1] : begin UNLOAD[0] = memel[MAXCHLEN-1+SIG_IDS_W:SIG_IDS_W]; end 
               default: begin  
                 $display("\nXTB Error: Wrong signal argument (%s) passed to load_unload procedure. Exiting...", SignalIDName[memel[SIG_IDS_W-1:0]]);
                 $finish; 
               end 
             endcase 
             na = na+1;
           end
             load_unload(sid_args, sval_args);
         end 
         'd`multiclock_captureStmt: begin: multiclock_capture_BLOCK
           cur_stmt = `multiclock_captureStmt;
           set_args(memel[20:16]);
             multiclock_capture(sid_args, sval_args);
         end 
         default: begin $display("\nXTB Error: Unrecognized code %0h, @ inst %0d", opcode, data_i); $finish; end 
       endcase 
       data_i = data_i + 1;
       popcode = opcode;
       if (verbose >= 3) display_stmt(cur_stmt);
     end 
     $display("XTB: Simulation of %0d pattern%s completed with %0d mismatch%s (time: %0t, cycles: %0d)\n", nbpats+end_pat-1, (nbpats==1)?"":"s", nbfails, (nbfails==1)?"":"es", $time, v_count); 

     if (diagf) $fclose(diagf);
     ->end_part;
   end 


   task init_rtops;
     integer i;
   begin
     for (i=0; i<`NBRTOPS; i=i+1)
       rt_ops[i] = -1;
     RT_OPS [0] = "tmax_n_pattern_sim";
     RT_OPS [1] = "tmax_serial";
     RT_OPS [2] = "tmax_parallel";
     RT_OPS [3] = "tmax_msg";
     RT_OPS [4] = "tmax_rpt";
     RT_OPS [5] = "tmax_test_setup_only_once";
     RT_OPS [6] = "tmax_usf_debug_strobe_mode"; 
   end 
   endtask

   task process_rtops;
     integer sim_op, p_mode;
     integer i, r;
   begin
     sim_op = -1;
     init_rtops;
     for (i=0; i<`NBRTOPS; i=i+1)
       r = $value$plusargs ({RT_OPS[i], "=%d"}, rt_ops[i]);
     if ((rt_ops[0] > -1)) last_pat = rt_ops[0];
     if (last_pat != total_pats-1) begin
       display_ops ((rt_ops[0] > 0), last_pat, RT_OPS[0]);
       $display("XTB: User requesting simulating patterns 0 to %0d",last_pat);
     end 
     if (last_pat >= total_pats && total_pats > 1) begin
       $display("XTB Error: Simulation patterns (%0d) exceeds total pattern count (%0d). Exiting...",  last_pat+1,total_pats);
       $finish;
     end 
     else if (last_pat < 0 && total_pats != 0)  begin 
       $display("XTB Error: User requesting simulating wrong number of patterns (%0d). Exiting... ",last_pat+1);
       $finish;
     end
     if ((rt_ops[1] > 0)) begin
       if (rt_ops[1]==0) ser_pats = last_pat + 1;
       else ser_pats = rt_ops[1];
       sim_op = 0;
     end 
     else if (rt_ops[1] != 0 &&  ($test$plusargs ("tmax_serial"))) begin
       ser_pats = last_pat + 1;
       rt_ops[1] = ser_pats;
       sim_op = 0;
     end
     if ((rt_ops[1]>0) || (csim_op==0 || csim_op==2)) display_ops ((rt_ops[1]>0), ser_pats, RT_OPS[1]);
     p_mode = ((rt_ops[2] > -1) || ($test$plusargs ("tmax_parallel")))?1:0;
     if (p_mode) begin
       SSHIFTS = (rt_ops[2] > -1)?rt_ops[2]:DFSHIFTS;
       if (sim_op == -1)
         sim_op = 1;
       else  if (ser_pats  < last_pat + 1)
         sim_op = 0;
       else 
         sim_op = 2;
     end 
     if (p_mode || (csim_op==1 || csim_op==2)) display_ops (p_mode, SSHIFTS, RT_OPS[2]);
     if (sim_op > -1)
       set_sim_ops (sim_op);
     else if (csim_op > -1)
       set_sim_ops (csim_op);
     if (rt_ops[3] > -1) begin
       verbose = rt_ops[3];
     end
     if (verbose != 0) 
       display_ops ((rt_ops[3]>-1), verbose, RT_OPS[3]);
     if (rt_ops[4] > -1) begin
       rep_pat =  rt_ops[4];
     end
     if (rep_pat != 5) 
       display_ops ((rt_ops[4]>-1), rep_pat, RT_OPS[4]);
     if (rt_ops[5] != 0 && ($test$plusargs ("tmax_test_setup_only_once"))) begin
       test_setup_only_once = 1;
       rt_ops[5] = 1;
     end
     if (test_setup_only_once > 0) begin
       display_ops ((rt_ops[5]>-1), test_setup_only_once, RT_OPS[5]);
     end
   end 
   endtask

   task display_ops;
     input reg rt;
     input integer val;
     input reg [32*8:1] opname;
   begin
     $display("XTB: Setting %0s option \"%0s\" to %0d.", (rt==1)?"runtime":"compile-time",  opname, val);
   end 
   endtask

   task display_help;
   integer op;
   begin
     init_rtops;
     $display("\n\n\t\t----------------------- Runtime Help ------------------------------\n");
     $display("XTB: Usage is: <sim_exec> +opt1=val1 +opt2=val2...");
     $display("     where  <sim_exec> is the simulation exec name, and opt1 opt2 are available options and val1, val2 their corresponding values.");
     $display("     Available runtime options are:");
     op = 0;
     while (op < `NBRTOPS) begin
       $display("        +%0s", RT_OPS[op]);
       op = op + 1;
     end
     $display("\n      E.g.: simv +tmax_serial=2 +tmax_msg=2, runs first 2 patterns in serial and remaining in parallel, and set the verbose msg level to 2.");
     $display("\n Note: Runtime options override corresponding compile-time options.");
     $display("\n       Please refer to the User's Guide for details regarding each option.");
     $display("\n\t\t-------------------------------------------------------------------\n");
   end 
   endtask

   task set_sim_ops;
     input integer smode;
   begin
     if (smode==0) begin 
       xtb_sim_mode = 0;
       $write("XTB: Enabling serial simulation for");
       if (ser_pats < last_pat + 1) begin
         if (ser_pats==1) $write(" the first pattern.\n");
         else $write(" first %0d patterns.\n", ser_pats);
       end else 
         $write(" all patterns.\n");
     end
     else if (smode==1) begin 
       $write("XTB: Enabling parallel simulation with %0d serial shift(s).\n", SSHIFTS);
       xtb_sim_mode = 1;
     end 
     else  if (smode==2) begin
       $display("XTB Warning: requesting full serial simulation and full parallel simulation in the same time. Performing default parallel simulation mode...");
       xtb_sim_mode = 1;
     end 
   end 
   endtask


   initial begin: _burst__pattern__init_unit

     `ifdef tmax_fsdb
       $fsdbDumpvars;
     `endif


     for (n=0; n<SIG_IDS; n=n+1) SignalIDWidth[n] = 0;
     SignalIDName[0] = "clk";
     SignalIDType[0] = 0; //clk
     SignalIDWidth[0] = 1; //clk
     SignalIDName[1] = "rst_n";
     SignalIDType[1] = 0; //rst_n
     SignalIDWidth[1] = 1; //rst_n
     SignalIDName[2] = "bist_start";
     SignalIDType[2] = 0; //bist_start
     SignalIDWidth[2] = 1; //bist_start
     SignalIDName[3] = "bist_resp[1]";
     SignalIDType[3] = 0; //\bist_resp[1] 
     SignalIDWidth[3] = 1; //\bist_resp[1] 
     SignalIDName[4] = "bist_resp[0]";
     SignalIDType[4] = 0; //\bist_resp[0] 
     SignalIDWidth[4] = 1; //\bist_resp[0] 
     SignalIDName[5] = "test_si";
     SignalIDType[5] = 0; //test_si
     SignalIDWidth[5] = 1; //test_si
     SignalIDName[6] = "test_se";
     SignalIDType[6] = 0; //test_se
     SignalIDWidth[6] = 1; //test_se
     SignalIDName[7] = "bist_cs";
     SignalIDType[7] = 1; //bist_cs
     SignalIDWidth[7] = 1; //bist_cs
     SignalIDName[8] = "bist_we";
     SignalIDType[8] = 1; //bist_we
     SignalIDWidth[8] = 1; //bist_we
     SignalIDName[9] = "bist_addr[3]";
     SignalIDType[9] = 1; //\bist_addr[3] 
     SignalIDWidth[9] = 1; //\bist_addr[3] 
     SignalIDName[10] = "bist_addr[2]";
     SignalIDType[10] = 1; //\bist_addr[2] 
     SignalIDWidth[10] = 1; //\bist_addr[2] 
     SignalIDName[11] = "bist_addr[1]";
     SignalIDType[11] = 1; //\bist_addr[1] 
     SignalIDWidth[11] = 1; //\bist_addr[1] 
     SignalIDName[12] = "bist_addr[0]";
     SignalIDType[12] = 1; //\bist_addr[0] 
     SignalIDWidth[12] = 1; //\bist_addr[0] 
     SignalIDName[13] = "bist_pat[1]";
     SignalIDType[13] = 1; //\bist_pat[1] 
     SignalIDWidth[13] = 1; //\bist_pat[1] 
     SignalIDName[14] = "bist_pat[0]";
     SignalIDType[14] = 1; //\bist_pat[0] 
     SignalIDWidth[14] = 1; //\bist_pat[0] 
     SignalIDName[15] = "bist_done";
     SignalIDType[15] = 1; //bist_done
     SignalIDWidth[15] = 1; //bist_done
     SignalIDName[16] = "pass_or_fail";
     SignalIDType[16] = 1; //pass_or_fail
     SignalIDWidth[16] = 1; //pass_or_fail
     SignalIDName[17] = "_pi";
     SignalIDType[17] = 3; //_pi
     SignalIDWidth[17] = 7; //_pi
     SignalIDName[18] = "all_inputs";
     SignalIDType[18] = 3; //all_inputs
     SignalIDWidth[18] = 7; //all_inputs
     SignalIDName[19] = "_po";
     SignalIDType[19] = 3; //_po
     SignalIDWidth[19] = 10; //_po
     SignalIDName[20] = "_si";
     SignalIDType[20] = 3; //_si
     SignalIDWidth[20] = 1; //_si
     SignalIDName[21] = "all_outputs";
     SignalIDType[21] = 3; //all_outputs
     SignalIDWidth[21] = 10; //all_outputs
     SignalIDName[22] = "_clk";
     SignalIDType[22] = 3; //_clk
     SignalIDWidth[22] = 2; //_clk
     SignalIDName[23] = "_so";
     SignalIDType[23] = 3; //_so
     SignalIDWidth[23] = 1; //_so
     WFTIDName[0] = "_multiclock_capture_WFT_";
     WFTIDName[1] = "_default_WFT_";
     StmtNames[0] = "EndPat";
     StmtNames[1] = "IncPat";
     StmtNames[2] = "SetPat";
     StmtNames[3] = "WFTStmt";
     StmtNames[4] = "ConditionStmt";
     StmtNames[5] = "VectorStmt";
     StmtNames[6] = "FixedStmt";
     StmtNames[7] = "GenLoopStmt";
     StmtNames[8] = "EndGenLoopStmt";
     StmtNames[9] = "GenTestSetupStmt";
     StmtNames[10] = "EndGenTestSetupStmt";
     StmtNames[11] = "SetForceSI";
     StmtNames[12] = "SetValidStrobe";
     StmtNames[13] = "AnnotationStmt";
     StmtNames[14] = "SetWPack";
     StmtNames[15] = "SetRPack";
     StmtNames[16] = "test_setupStmt";
     StmtNames[17] = "load_unloadStmt";
     StmtNames[18] = "multiclock_captureStmt";

     $display("%s",`MAXTB_H_S);
     $display("%s",`MAXTB_HEADER);
     $display("%s\n",`MAXTB_H_S);

     if ( $test$plusargs ("tmax_help") ) begin
       display_help;
       $finish(0);
     end

     $timeformat(-9,2," ns",19);

     `ifdef tmax_test_data_file 
       tdfm = 1;
       TDATA_FILE = `tmax_test_data_file ;
     `else
       tdfm = 0;
       TDATA_FILE = `TDATA_FILE ;
     `endif


     `ifdef tmax_vcde
       $display("XTB: Dumping Extended VCD information in file \"top_dft_tb.vcd\"");
       $dumpports(`XTB_DUT_HIER, "top_dft_tb.vcd");
     `endif

     `ifdef tmax_msg
       verbose = `tmax_msg ;
     `else
       verbose = 0 ;
     `endif

     `ifdef tmax_debug
     if (~(`tmax_debug & 1'b1) == 1'b0)
       debug = 1;
     else
       debug = `tmax_debug + 0 ;
     `else
     debug = 0 ;
     `endif

     `ifdef tmax_rpt
     rep_pat = `tmax_rpt ;
     `else
     rep_pat = 5 ;
     `endif

     test_setup_runs = 0;

     CH_NAMES[0] = "1";
     CH_PINS[0] = "bist_pat[1]";
     CH_OUTINV[0] = 21'b000000000000000000000;
     CH_INPINV[0] = 21'b000000000000000000000;

     diagm = 0;
     diag_file = "";

     `ifdef tmax_diag 
       diagm = `tmax_diag;
     `endif

     -> start_part;
     @(end_part) #0;
     $finish(0);

   end

 endmodule
